In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Safna's Project/Merged_DF/Merged_DF.csv",index_col='Unnamed: 0')

In [ ]:
df

age  ILMN_1653355  ...  ethinicity_encoded  gender_encoded
0     65      7.650277  ...                  16               0
1     66      7.905123  ...                  14               0
2     67      7.610028  ...                  16               0
3     67      7.647674  ...                  15               0
4     67      7.676041  ...                  16               0
..   ...           ...  ...                 ...             ...
712   83      6.025457  ...                  16               0
713   83      6.091774  ...                  16               0
714   82      6.088321  ...                  16               1
715   88      6.005137  ...                  16               1
716   86      6.116739  ...                   7               0

[717 rows x 9612 columns]

In [ ]:
X = df.drop('status_encoded',axis=1)
y = df['status_encoded']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA()
X_train_ = lda.fit_transform(X_train,y_train)
X_test_  = lda.transform(X_test)

In [ ]:
X_train_.shape

(573, 2)

In [ ]:
X_test_.shape

(144, 2)

In [ ]:
lda.explained_variance_ratio_

array([0.64594606, 0.35405394])

In [ ]:
# from sklearn.preprocessing import StandardScaler

# sc = StandardScaler()
# X_train_ = sc.fit_transform(X_train)
# X_test_  = sc.transform(X_test)

In [ ]:
y_train

707    0
283    1
206    0
502    0
144    0
      ..
109    0
331    2
6      2
536    0
577    2
Name: status_encoded, Length: 573, dtype: int64

In [ ]:
X_train_

array([[-1.63983349e+00, -1.45893150e+00],
       [ 2.16052673e+00, -1.47963782e+00],
       [-3.10050959e+00, -9.40020330e-01],
       ...,
       [ 9.45429737e-02,  2.75955069e+00],
       [-1.16137054e+00, -1.20872837e+00],
       [ 5.79054930e-01, -2.24457492e-04]])

In [ ]:
configurations_v1 = {
    'config1': {'solver': 'newton-cg', 'random_state': 0, 'penalty': 'l2', 'C': 1.0, 'dual': False},
    # 'config2': {'solver': 'newton-cg', 'random_state': 0, 'penalty': 'l1', 'C': 10.0, 'dual': False},
    'config3': {'solver': 'newton-cg', 'random_state': 0, 'penalty': 'l2', 'C': 10.0, 'dual': False},
    # 'config4': {'solver': 'newton-cg', 'random_state': 0, 'penalty': 'l1', 'C': 1.0, 'dual': False},
    # 'config5': {'solver': 'newton-cg', 'random_state': 1, 'penalty': 'l1', 'C': 1.0, 'dual': False},
    'config6': {'solver': 'newton-cg', 'random_state': 1, 'penalty': 'l2', 'C': 1.0, 'dual': False},
    # 'config7': {'solver': 'newton-cg', 'random_state': 1, 'penalty': 'l1', 'C': 10.0, 'dual': False},
    'config8': {'solver': 'newton-cg', 'random_state': 1, 'penalty': 'l2', 'C': 10.0, 'dual': False},
    'config9': {'solver': 'newton-cg', 'random_state': 0, 'penalty': 'l2', 'C': 1.0, 'dual': True},
    # 'config10': {'solver': 'newton-cg', 'random_state': 0, 'penalty': 'l1', 'C': 1.0, 'dual': True},
    'config11': {'solver': 'newton-cg', 'random_state': 0, 'penalty': 'l2', 'C': 10.0, 'dual': True},
    # 'config12': {'solver': 'newton-cg', 'random_state': 0, 'penalty': 'l1', 'C': 10.0, 'dual': True},
    'config13': {'solver': 'newton-cg', 'random_state': 1, 'penalty': 'l2', 'C': 1.0, 'dual': True},
    # 'config14': {'solver': 'newton-cg', 'random_state': 1, 'penalty': 'l1', 'C': 1.0, 'dual': True},
    'config15': {'solver': 'newton-cg', 'random_state': 1, 'penalty': 'l2', 'C': 10.0, 'dual': True},
    # 'config16': {'solver': 'newton-cg', 'random_state': 1, 'penalty': 'l1', 'C':10.0, 'dual':True}
}

In [ ]:
configurations = {
    'config1': {'solver': 'liblinear', 'random_state': 0, 'penalty': 'l2', 'C': 1.0, 'dual': False},
    'config2': {'solver': 'liblinear', 'random_state': 0, 'penalty': 'l1', 'C': 10.0, 'dual': False},
    'config3': {'solver': 'liblinear', 'random_state': 0, 'penalty': 'l2', 'C': 10.0, 'dual': False},
    'config4': {'solver': 'liblinear', 'random_state': 0, 'penalty': 'l1', 'C': 1.0, 'dual': False},
    'config5': {'solver': 'liblinear', 'random_state': 1, 'penalty': 'l1', 'C': 1.0, 'dual': False},
    'config6': {'solver': 'liblinear', 'random_state': 1, 'penalty': 'l2', 'C': 1.0, 'dual': False},
    'config7': {'solver': 'liblinear', 'random_state': 1, 'penalty': 'l1', 'C': 10.0, 'dual': False},
    'config8': {'solver': 'liblinear', 'random_state': 1, 'penalty': 'l2', 'C': 10.0, 'dual': False},
    'config9': {'solver': 'liblinear', 'random_state': 0, 'penalty': 'l2', 'C': 1.0, 'dual': True},
    'config10': {'solver': 'liblinear', 'random_state': 0, 'penalty': 'l1', 'C': 1.0, 'dual': True},
    'config11': {'solver': 'liblinear', 'random_state': 0, 'penalty': 'l2', 'C': 10.0, 'dual': True},
    'config12': {'solver': 'liblinear', 'random_state': 0, 'penalty': 'l1', 'C': 10.0, 'dual': True},
    'config13': {'solver': 'liblinear', 'random_state': 1, 'penalty': 'l2', 'C': 1.0, 'dual': True},
    'config14': {'solver': 'liblinear', 'random_state': 1, 'penalty': 'l1', 'C': 1.0, 'dual': True},
    'config15': {'solver': 'liblinear', 'random_state': 1, 'penalty': 'l2', 'C': 10.0, 'dual': True},
    'config16': {'solver': 'liblinear', 'random_state': 1, 'penalty': 'l1', 'C':10.0, 'dual':True}
}

In [ ]:
configurations_CV = {
    'config1': {'solver': 'liblinear', 'random_state': 0, 'penalty': 'l2', 'C': 1.0, 'dual': False, 'cv':10},
    'config2': {'solver': 'liblinear', 'random_state': 0, 'penalty': 'l2', 'C': 10.0, 'dual': False, 'cv':20},
    'config3': {'solver': 'liblinear', 'random_state': 0, 'penalty': 'l2', 'C': 10.0, 'dual': False, 'cv':10},
    'config4': {'solver': 'liblinear', 'random_state': 0, 'penalty': 'l2', 'C': 1.0, 'dual': False, 'cv':20},
    'config5': {'solver': 'liblinear', 'random_state': 1, 'penalty': 'l2', 'C': 1.0, 'dual': False, 'cv':20},
    'config6': {'solver': 'liblinear', 'random_state': 1, 'penalty': 'l2', 'C': 1.0, 'dual': False, 'cv':10},
    'config7': {'solver': 'liblinear', 'random_state': 1, 'penalty': 'l2', 'C': 10.0, 'dual': False, 'cv':20},
    'config8': {'solver': 'liblinear', 'random_state': 1, 'penalty': 'l2', 'C': 10.0, 'dual': False, 'cv':10},
    'config9': {'solver': 'liblinear', 'random_state': 0, 'penalty': 'l2', 'C': 1.0, 'dual': True, 'cv':10},
    'config10': {'solver': 'liblinear', 'random_state': 0, 'penalty': 'l2', 'C': 1.0, 'dual': True, 'cv':20},
    'config11': {'solver': 'liblinear', 'random_state': 0, 'penalty': 'l2', 'C': 10.0, 'dual': True, 'cv':10},
    'config12': {'solver': 'liblinear', 'random_state': 0, 'penalty': 'l2', 'C': 10.0, 'dual': True, 'cv':20},
    'config13': {'solver': 'liblinear', 'random_state': 1, 'penalty': 'l2', 'C': 1.0, 'dual': True, 'cv':10},
    'config14': {'solver': 'liblinear', 'random_state': 1, 'penalty': 'l2', 'C': 1.0, 'dual': True, 'cv':20},
    'config15': {'solver': 'liblinear', 'random_state': 1, 'penalty': 'l2', 'C': 10.0, 'dual': True, 'cv':10},
    'config16': {'solver': 'liblinear', 'random_state': 1, 'penalty': 'l2', 'C':10.0, 'dual':True, 'cv':20}
}

In [ ]:
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, mean_squared_error, r2_score
from math import sqrt

In [ ]:
X_test_

array([[ 2.25473373e+00, -5.34094612e+00],
       [-1.46344197e+00,  1.43367203e+00],
       [-1.78999988e+00, -3.37129170e+00],
       [ 3.91382319e-01,  1.00674668e+00],
       [ 1.40133585e+00,  1.62794470e-02],
       [-2.20887307e+00,  1.10639472e+00],
       [ 8.00823812e-02,  1.10139380e+00],
       [ 4.02698207e+00,  5.78717828e-01],
       [-2.78999509e+00,  7.40738639e-01],
       [ 3.64877800e+00,  9.80256701e-01],
       [-7.16201383e-01, -1.41488354e+00],
       [-1.83619547e+00,  5.92681706e-01],
       [-2.37234044e+00,  2.36764838e+00],
       [-2.98828094e+00, -3.87835029e-01],
       [-3.17973507e+00, -6.04417797e-01],
       [-8.20039932e-01,  7.14693535e-01],
       [ 3.95215431e-01, -1.49787325e+00],
       [-5.44527724e+00,  3.12087347e+00],
       [ 1.30466058e-01,  1.83819605e-02],
       [-4.15280694e+00, -9.29482036e-01],
       [-4.43246834e-01,  5.19682901e-01],
       [-2.87102904e+00, -1.63358390e+00],
       [ 2.24803264e-01, -8.52948357e-01],
       [ 9.

In [ ]:
for configs in configurations:
  print("*************************************************************")
  print(configs)
  model = LogisticRegression(solver = configurations[configs]['solver'], random_state=configurations[configs]['random_state'], penalty=configurations[configs]['penalty'], C=configurations[configs]['C'])
  model.fit(X_train_, y_train)
  print("Model Score: ",model.score(X_train_,y_train))
  print("Accuracy Score:", accuracy_score(y_test,model.predict(X_test_)))
  print(classification_report(y_test, model.predict(X_test_)))
  print("RMSE Value (Train)", sqrt(mean_squared_error(y_train,model.predict(X_train_))))
  print("RMSE Value (Test): ", sqrt((mean_squared_error(y_test, model.predict(X_test_)))))
  print("R-Squared Value (Test): ", r2_score(y_test, model.predict(X_test_)))
  
  print("*************************************************************\n")


*************************************************************
config1
Model Score:  0.9109947643979057
Accuracy Score: 0.5694444444444444
              precision    recall  f1-score   support

           0       0.63      0.60      0.62        63
           1       0.66      0.60      0.62        42
           2       0.41      0.49      0.45        39

    accuracy                           0.57       144
   macro avg       0.57      0.56      0.56       144
weighted avg       0.58      0.57      0.57       144

RMSE Value (Train) 0.40286929011959444
RMSE Value (Test):  1.0474837574980447
R-Squared Value (Test):  -0.6122448979591839
*************************************************************

*************************************************************
config2
Model Score:  0.9092495636998255
Accuracy Score: 0.5694444444444444
              precision    recall  f1-score   support

           0       0.63      0.60      0.62        63
           1       0.66      0.60      0.62     

In [ ]:
for configs in configurations_v1:
  print("*************************************************************")
  print(configs)
  model = LogisticRegression(solver = configurations_v1[configs]['solver'], random_state=configurations_v1[configs]['random_state'], penalty=configurations_v1[configs]['penalty'], C=configurations_v1[configs]['C'])
  model.fit(X_train_, y_train)
  print("Model Score: ",model.score(X_train_,y_train))
  print("Accuracy Score:", accuracy_score(y_test,model.predict(X_test_)))
  print(classification_report(y_test, model.predict(X_test_)))
  print("RMSE Value (Train)", sqrt(mean_squared_error(y_train,model.predict(X_train_))))
  print("RMSE Value (Test): ", sqrt((mean_squared_error(y_test, model.predict(X_test_)))))
  print("R-Squared Value (Test): ", r2_score(y_test, model.predict(X_test_)))
  
  print("*************************************************************\n")


*************************************************************
config1
Model Score:  0.8
Accuracy Score: 0.5888501742160279
              precision    recall  f1-score   support

           0       0.60      0.67      0.63       116
           1       0.61      0.68      0.64        87
           2       0.53      0.38      0.44        84

    accuracy                           0.59       287
   macro avg       0.58      0.58      0.57       287
weighted avg       0.58      0.59      0.58       287

RMSE Value (Train) 0.6342914010100947
RMSE Value (Test):  0.9770894701881775
R-Squared Value (Test):  -0.3948843479494819
*************************************************************

*************************************************************
config3
Model Score:  0.8
Accuracy Score: 0.5888501742160279
              precision    recall  f1-score   support

           0       0.60      0.67      0.63       116
           1       0.61      0.68      0.64        87
           2       0.53  

In [ ]:
for configs in configurations_CV:
  print("*************************************************************")
  print(configs)
  print(configurations_CV[configs])
  model = LogisticRegressionCV(cv=configurations_CV[configs]['cv'],solver = configurations_CV[configs]['solver'], random_state=configurations_CV[configs]['random_state'], penalty=configurations_CV[configs]['penalty'])
  model.fit(X_train_, y_train)
  print("Model Score: ",model.score(X_train_,y_train))
  print("Accuracy Score:", accuracy_score(y_test,model.predict(X_test_)))
  print(classification_report(y_test, model.predict(X_test_)))
  print("RMSE Value (Train)", sqrt(mean_squared_error(y_train,model.predict(X_train_))))
  print("RMSE Value (Test): ", sqrt((mean_squared_error(y_test, model.predict(X_test_)))))
  print("R-Squared Value (Test): ", r2_score(y_test, model.predict(X_test_)))
  
  print("*************************************************************\n")

*************************************************************
config1
{'solver': 'liblinear', 'random_state': 0, 'penalty': 'l2', 'C': 1.0, 'dual': False, 'cv': 10}
Model Score:  0.786046511627907
Accuracy Score: 0.5679442508710801
              precision    recall  f1-score   support

           0       0.53      0.72      0.61       116
           1       0.64      0.60      0.62        87
           2       0.56      0.33      0.42        84

    accuracy                           0.57       287
   macro avg       0.58      0.55      0.55       287
weighted avg       0.57      0.57      0.56       287

RMSE Value (Train) 0.6505811355653408
RMSE Value (Test):  1.0291906769288925
R-Squared Value (Test):  -0.5476089115935856
*************************************************************

*************************************************************
config2
{'solver': 'liblinear', 'random_state': 0, 'penalty': 'l2', 'C': 10.0, 'dual': False, 'cv': 20}
Model Score:  0.7906976744186046
Acc